### ISSUE TITLE
Add a "Community supported" to the landing page

### ISSUE THREAD

**Issue by almet** [thelounge/thelounge.github.io#12]
This is a spin-off of #9. A new item could be added to the landing page, explaining why the fact it's community supported matters.

First try:

```md
# Community supported

The development of TheLounge is made by a growing and dedicated community of people.
We try our best to be as friendly as possible and welcome any contributions.
(The Lounge is a fork of Shout, you can read more about it here [link]).
```

**Comment by astorije** [comment]
Nice!

Some comments:
- s/supported/managed/
- s/TheLounge/The Lounge/
- Maybe a link to the CONTRIBUTING file on "welcome any contributions" (contributions are always more welcome after they are discussed over an issue or on the channel :-) )

**Comment by JocelynDelalande** [comment]
Ok for me, nothing to add on top of @astorije feedback.

@almet is your intent to `(link)` to https://github.com/thelounge/lounge/wiki/Differences-between-The-Lounge-and-Shout ?

**Comment by astorije** [comment]
@JocelynDelalande, I might be wrong, but I believed the intent was https://github.com/thelounge/lounge/blob/master/README.md#the-lounge (although, if so, "Why the fork?" should probably be a title instead of a `<strong>` to provide us with an anchor).

**Comment by JocelynDelalande** [comment]
@astorije you are maybe right, just asking to be sure what we are speaking about :)

**Comment by almet** [comment]
I wanted to link to the README and "why the fork" section, which would then maybe need to have a anchor.

But I wasn't aware of this wiki page listing the differences, and that might be an even better resource to link to!

**Comment by almet** [comment]
After reading a bit more in the wiki page, it doesn't list any ethical or organisational differences, so I believe we should either:

- improve the wiki page to list what are the organisational / ethical differences between the two projects;
- link to the "why the fork" section and create an anchor for it.

**Comment by JocelynDelalande** [comment]
> - improve the wiki page to list what are the organisational / ethical differences between the two projects;
> - link to the "why the fork" section and create an anchor for it.

There is a third way : link to both :-)

**Comment by astorije** [comment]
I'm OK with either the second item or the one @JocelynDelalande mentioned. This wiki page only lists technical differences on purpose.

**Comment by xPaw** [comment]
We still need to add this. When people look at lounge site, they think it's a shout clone as we don't explain the fork anywhere.

**Comment by astorije** [comment]
This has been done in #41.
