### ISSUE TITLE
Write page "Set up ZNC with The Lounge"

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#149]
Would live at http://thelounge.chat/docs/guides/znc

Point out that you might need to use ZNC at all.

**Comment by brunnre8** [comment]
What would you like to see in the guide?
I mean znc behaves exactly like a server there's nothing special from the lounge's side of things

**Comment by xPaw** [comment]
That's kind of the point that it works out of the box.

However the page would be used to say a couple of things:

1. You might need ZNC at all as The Lounge works similarly to a bouncer.
2. If you end up using ZNC, you might want to use [Playback](https://wiki.znc.in/Playback) module so that Lounge can request only new messages whenever it reconnects.

**Comment by astorije** [comment]
I think a short intro about what ZNC is (with links to more comprehensive descriptions/tutorials), why you might want to use it or not use it along with The Lounge might be useful.

People have mentioned using ZNC is useful when using other clients as well, or to get push notifications when we can't provide it ourselves. Arguments to use ZNC are fewer and fewer (i.e. push notifications use pretty everywhere but iOS now), but I believe there are still a couple.
Could also be useful if you want to run multiple versions of TL, like one stable version in prod + share the data to use a development version. Again less useful now that we have history reloading (and I believe @xPaw and @McInkay are using it for this reason, I don't), but maybe worth noting.
