### ISSUE TITLE
Add short descriptions for each individual page

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#153]
So that we can do this: https://sarathlal.com/add-meta-description-in-jekyll-posts/

**Comment by astorije** [comment]
For whoever takes it, quick FYI, I am currently using `description` in the API pages only at the moment, to build the index: https://github.com/thelounge/thelounge.github.io/blame/master/_api/stylesheets.md#L4. We might want to either rename that field, or not, depending if it can be reused directly or not.
