### ISSUE TITLE
Deny robots on 'next' subdomain

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#172]
We wouldn't want search engines to accidentally index that.

I presume we can detect the branch name when netlify is deploying, and change robots.txt into a template which put this in robots:

```
User-agent: *
Disallow: /
```

**Comment by astorije** [comment]
Oh, duh, just saw this. So yeah my `JEKYLL_ENV=production` isn't good enough and require more, e.g. by using `ENV['CONTEXT']`.
See https://www.netlify.com/docs/continuous-deployment/#deploy-contexts and https://www.netlify.com/docs/continuous-deployment/#build-environment-variables
