### ISSUE TITLE
Link anchor icon is off screen on mobile

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#199]
Since it has an absolute position to the left of the headers, it can overflow out of view.

**Comment by astorije** [comment]
On mobile, we could position it after the text.

On top of that, the icon only shows up on hover. I was considering making the whole title clickable, maybe always display the icon on mobile, but not sure if that would be a good idea as some titles have links (which might not be a good thing on its own).

In terms of use case, I'm not sure if this feature is very useful on mobile as opposed to desktop. No strong opinions, just wondering.

**Comment by xPaw** [comment]
> In terms of use case, I'm not sure if this feature is very useful on mobile as opposed to desktop. 

I needed to link something on mobile, which is why I noticed it in the first place.
