### ISSUE TITLE
Add most basic example of config.js

### ISSUE THREAD

**Issue by Industrial** [thelounge/thelounge.github.io#239]
Hi!

I'm missing an example of how the `config.js` file is structured.

I read "Start by locating the config.js file in the configuration folder, which depends on how you installed The Lounge." but I am using the Docker image so I don't have a config.js anywhere.

I've created a Dockerfile with:

```docker
FROM thelounge/thelounge

ADD config.js /var/opt/thelounge/
```

I would expect there to be a minimal example of the complete config.js e.g. (not sure if this is correct)

```js
module.exports = {
  // options here
}
```

This way it's very clear what the file should look like.

gr,

Tom

**Comment by xnaas** [comment]
https://github.com/thelounge/thelounge/blob/master/defaults/config.js seens fairly straight-forward. If you correctly mounted a volume for the docker container, you most definitely have a config.js somewhere. Where depends on what you did.
