### ISSUE TITLE
Add documentation on how to proxy behind common web servers

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#24]
http://nginx.org/en/docs/http/websocket.html
https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel

**Comment by swordbeta** [comment]
Can be found on the wiki as you're probably aware of since you created it: https://github.com/thelounge/lounge/wiki/Reverse-Proxies
Issue can be closed or are we planning on moving it to the documentation website?

**Comment by astorije** [comment]
@swordbeta, it was proposed in https://github.com/thelounge/thelounge.github.io/pull/58 but paused as I'm completely reworking the documentation right now (see https://github.com/thelounge/thelounge.github.io/tree/astorije/better-docs + a whole set of unpushed commits I have and plan to push very soon).
Feel free to ping me in private message on IRC if you want to help with this :)
