### ISSUE TITLE
Documentation recommends using non-supported Node.js

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge.github.io#25]
The [install doc for Ubuntu and Debian](https://thelounge.github.io/docs/getting_started/install.html#ubuntu-debian) says to install Node.js with:

``` sh
sudo apt-get -y install nodejs-legacy npm
```

On Debian Jessie, [`nodejs-legacy` is in v0.10](https://packages.debian.org/jessie/nodejs-legacy). It [goes to v4.x in Stretch only](https://packages.debian.org/stretch/nodejs-legacy), which will not be here before a year.

[Same with Ubuntu Trusty Tahr](http://packages.ubuntu.com/trusty/nodejs-legacy), the current LTS and the following version, [Wily Werefolf](http://packages.ubuntu.com/wily/nodejs-legacy). It's in v4.x only since the last version, [Xenial Xerus, released 2 months ago](http://packages.ubuntu.com/xenial/nodejs-legacy).

Considering we are dropping support for Node.js v0.10, we should probably specify in the doc that, unless people are running Debian Stretch or Ubuntu Xenial Xerus, they should be installing Node through Nodesource or whatever instead of `apt-get`. Any suggestions? (Ping @JocelynDelalande, it's been a while 😄).

**Comment by JocelynDelalande** [comment]
I wanted to opened the very same ticket, so thanks for that :-)

> Considering we are dropping support for Node.js v0.10, we should probably specify in the doc that, unless people are running Debian Stretch or Ubuntu Xenial Xerus, they should be installing Node through Nodesource or whatever instead of apt-get. Any suggestions?.

Nodesource Debian repository are the simplest way I know at the moment.

> (Ping @JocelynDelalande, it's been a while 😄).

;-) quite busy…
