### ISSUE TITLE
Heroku docs suggest cloning from git

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge.github.io#30]
We should suggest installing released versions.

**Comment by astorije** [comment]
So Passenger doc has been removed from the v3 doc redesign, and Heroku doc has been marked as "unofficial". It has another issue or 2 on top of this, do we want to keep it alive? No one in the core team uses Heroku and it makes maintaining the guide a hassle.
@xPaw, thoughts?

@dideler, @kosmita123, would you be willing to help [on the Heroku doc](https://github.com/thelounge/thelounge.github.io/blob/master/_docs/unofficial-install-methods/heroku.md)?

**Comment by xPaw** [comment]
I think we can replace `Build The Lounge` section with `yarn install`?

**Comment by dideler** [comment]
> @dideler, @kosmita123, would you be willing to help on the Heroku doc?

Sorry can't help here as I've moved away from Lounge and IRC in general over a year ago.
