### ISSUE TITLE
User changes nick, client doesn't follow.

### ISSUE THREAD

**Issue by henry158** [thelounge/thelounge.github.io#37]
I have come to this client from Irssi, and when a user in a query with yourself, if they change nicks the server follows that change  and update see [here](https://github.com/irssi/irssi/blob/master/src/fe-common/irc/fe-irc-queries.c) for the the specific c file for how it is handled.

It would be nice to see this added, I have little to no (node)js experience at all or I'd do it myself.

**Comment by astorije** [comment]
Hey @henry158! That's a good idea and would probably not too hard to implement right. However, you're on the wrong repository, this is for the presentation website and documentation. Could you re-open your enhancement request at https://github.com/thelounge/lounge please?
Thanks!
