### ISSUE TITLE
Generated config missing home option

### ISSUE THREAD

**Issue by dideler** [thelounge/thelounge.github.io#62]
While trying to configure the default `HOME` location, I noticed the config that's autogenerated to `~/.lounge/config.js` is missing the [home option that's specified in the config docs](https://thelounge.github.io/docs/server/configuration.html#home).

It's unclear to me what the desired behaviour is. Is this option deprecated and the docs are outdated? Or are the docs correct and the option should be included in the config?

**Comment by astorije** [comment]
Hey @dideler! Browsing the history, I can't even find where that option was removed. I can't even tell you for sure if it has ever been a thing :D

So to answer your question, yes this option is unsupported and I have even removed it [in the complete doc rewrite that I'm actively working on right now](https://github.com/thelounge/thelounge.github.io/commit/f2848df1ad606279eafb902dafb1d83362389735#diff-79668e76b304ebe02151ea993a75fa46L157).

Regarding the desired behavior, well, that's precisely why this option would be so broken: it's a field in the configuration file to instruct The Lounge where to look for... the configuration file!
There are 2 alternatives to this at the moment: either use the `--home` CLI option (`lounge start --home /etc/lounge/`) or the `$LOUNGE_HOME` environment variable (`LOUNGE_HOME=/etc/lounge lounge start`). Happy to hear suggestions to improve this.

**Comment by dideler** [comment]
Yeah you're right, realised that the suggested Procfile for Heroku specifies the home path:
```
web: node index --private --home /app
```

Didn't know about the `LOUNGE_HOME` env var, thanks.

I'll leave this issue open so it can be resolved when your docs branch is merged.

**Comment by astorije** [comment]
Just an FYI, as of upcoming v2.5.0, `--home` will be deprecated in favor of the `LOUNGE_HOME` environment variable.
There will also be a `.lounge_home` file in the folder where The Lounge is installed, but while anyone can edit this, it is more intended for package installers that install in non-default locations, like https://github.com/thelounge/deb-lounge in `/etc/lounge`.
